version: "3"
name: "qst-0202"
services:
  qst-0202:
    container_name: "qst-0202-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/app/