version: "3"
name: "qst-0201"
services:
  qst-0301:
    container_name: "qst-0201-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend/app:/usr/share/nginx/app/