server {
    listen 80;
    server_name aaa.example.com;

    root /usr/share/nginx/aaa;
    index index.html;
}

server {
    listen 80;
    server_name bbb.example.com;

    root /usr/share/nginx/bbb;
    index index.html;
}
